#!/bin/sh

# Get the directory containing this script, see
# https://stackoverflow.com/a/29835459/704831
docs_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$docs_dir"

input_format=gfm-hard_line_breaks

# Generate combined markdown document for README.md
pandoc --from="$input_format" \
       --to=gfm-raw_html \
       --output=../README.md \
       --standalone \
       --template=template.readme \
       --toc \
       features.md \
       reference-syntax.md \
       reference-units.md \
       pros-and-cons.md \
       faq.md \
       terminal-version.md \
       development.md &

# Generate manpage
pandoc --from="$input_format" \
       --to=man \
       --output=insect.1 \
       --standalone \
       --reference-links \
       -V section=1 \
       -V header="insect - scientific calculator" \
       manpage-header.md \
       features.md \
       reference-syntax.md \
       faq.md \
       manpage-footer.md &

wait
